### ISSUE TITLE
Wrong link on the official extension page

### ISSUE THREAD

**Issue by dylantientcheu** [ardisaurus/vscode-gitflow#3]
On the VSCode extension marketplace;

https://marketplace.visualstudio.com/items?itemName=ardisaurus.gitflow-actions-sidebar

The link to the github at the bottom goes [somewhere else](https://github.com/vector-of-bool/vscode-gitflow)

**Comment by ardisaurus** [comment]
Thanks for the feedback, I fix it soon

**Comment by ardisaurus** [comment]
I fixed it
