### ISSUE TITLE
Please add to Open VSX registry

### ISSUE THREAD

**Issue by BrianGilbert** [ardisaurus/vscode-gitflow#8]
https://open-vsx.org/

The Open VSX Registry offers a community driven, fully open platform for publishing and consuming VS Code extensions. The Registry is built on Eclipse Open VSX, which is an open source project hosted at the Eclipse Foundation.

Open VSX is integrated into multiple software applications that support VS Code extensions. There is strong demand for a fully open alternative to the Visual Studio Marketplace, and with hundreds of great extensions already available, it is the intent of the Eclipse Foundation to enable continued and accelerated growth.

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by BrianGilbert** [comment]
My PR isn't the preferred method of publication, but would allow us to use it until the maintainer does the above.

**Comment by ardisaurus** [comment]
I just published it on Open VSX.
https://open-vsx.org/extension/ardisaurus/gitflow-actions-sidebar
